"""Interface for search dish api."""
from ..context import DishInBotRepr
from abc import ABC, abstractmethod


class BaseDishSearcher(ABC):
    """Interface for Dish Search API."""

    @abstractmethod
    def get_dishes(self, ingredients: str) -> list[DishInBotRepr]:
        """Return list dishes that were generated by ingredients."""
